name: Integration Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  linux-headless:
    runs-on: arc-runner-set
    container: golang:latest
    steps:
      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: CGO_ENABLED=1 go build .

  tests:
    runs-on: arc-runner-set
    container: golang:latest
    steps:
      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Go tests
        run: CGO_ENABLED=1 go test ./... -v

  staticcheck:
    runs-on: arc-runner-set
    container: golang:latest
    steps:
      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run static checks
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
